backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "/images"

locale: "pl"

collections:
  - name: "pages"
    label: "Strony"
    folder: "content/landing-pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nazwa strony", name: "title", widget: "string" }
      - { label: "Szablon", name: "template", widget: "select", options: ["duży", "średni", "mały"] }
      - { label: "Treść strony", name: "body", widget: "markdown" }
