backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: landing-pages
    label: Landing Pages
    folder: content/landing-pages
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Template", name: "template", widget: "select", options: ["large-page", "medium-page", "small-page"] }
      - { label: "Hero Title", name: "hero_title", widget: "string" }
      - { label: "Hero Subtitle", name: "hero_subtitle", widget: "string" }
      - { label: "CTA Text", name: "cta_text", widget: "string" }
      - { label: "Is Copy", name: "is_copy", widget: "boolean", default: false }
      - label: "Popup HTML"
        name: "popup_html"
        widget: "code"
      - label: "Features"
        name: "features"
        widget: "list"
        field:
          label: "Feature"
          name: "feature"
          widget: "string"
      - label: "Testimonials"
        name: "testimonials"
        widget: "list"
        field:
          label: "Testimonial"
          name: "testimonial"
          widget: "string"
      - { label: "Offer", name: "offer", widget: "string" }
      - label: "FAQ"
        name: "faq"
        widget: "list"
        fields:
          - { label: "Question", name: "question", widget: "string" }
          - { label: "Answer", name: "answer", widget: "text" }
      - label: "Countdown"
        name: "countdown"
        widget: "object"
        fields:
          - { label: "End Date", name: "end", widget: "datetime", required: false }
          - { label: "Text Before", name: "pre_text", widget: "string", required: false }
          - { label: "Text After", name: "post_text", widget: "string", required: false }
          - label: "Action After"
            name: "action"
            widget: "select"
            required: false
            options: ["none", "hide", "redirect"]

  - name: landing-list
    label: Lista landingów
    folder: content/landing-list
    create: true
    slug: landing-list
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }

  - name: links
    label: Список посилань
    files:
      - file: "public/links.html"
        label: links.html
        name: links
        fields:
          - label: "HTML вміст"
            name: body
            widget: "text"

  - name: site-settings
    label: "Site Settings"
    files:
      - file: "data/site_settings.yml"
        label: "General"
        name: "general"
        fields:
          - { label: "Head Code", name: "head_code", widget: "code", required: false }
          - { label: "Body Code", name: "body_code", widget: "code", required: false }
          - { label: "Favicon", name: "favicon", widget: "image", required: false }
