backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "/images"

locales:
  default: pl
  pl:
    buttons:
      create: "Utwórz"
      delete: "Usuń"
      edit: "Edytuj"
      publish: "Opublikuj"
      save: "Zapisz"
    collections:
      landing-pages: "Strony docelowe"
      landing-list: "Lista landingów"
      links: "Ustawienia strony"
    menu:
      media: "Multimedia"
      contents: "Treść"

collections:
  - name: landing-pages
    label: Strony docelowe
    label_singular: Strona
    create: true
    folder: content/landing-pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Template", name: "template", widget: "select", options: ["large-page", "medium-page", "small-page"] }
      - { label: "Hero Title", name: "hero_title", widget: "string" }
      - { label: "Hero Subtitle", name: "hero_subtitle", widget: "string" }
      - { label: "CTA Text", name: "cta_text", widget: "string" }
      - label: "Features"
        name: "features"
        widget: "list"
        field:
          label: "Feature"
          name: "feature"
          widget: "string"
      - label: "Testimonials"
        name: "testimonials"
        widget: "list"
        field:
          label: "Testimonial"
          name: "testimonial"
          widget: "string"
      - { label: "Offer", name: "offer", widget: "string" }
      - label: "FAQ"
        name: "faq"
        widget: "list"
        fields:
          - { label: "Question", name: "question", widget: "string" }
          - { label: "Answer", name: "answer", widget: "text" }

  - name: landing-list
    label: Lista landingów
    folder: content/landing-list
    create: true
    slug: landing-list
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }

  - name: links
    label: Ustawienia strony
    files:
      - file: "public/links.html"
        label: links.html
        name: links
        fields:
          - label: "HTML вміст"
            name: body
            widget: "text"
