backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Сторінки"
    folder: "content/landing-pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Назва", name: "title", widget: "string" }
      - { label: "Тип шаблону", name: "template_type", widget: "select", options: ["large", "medium", "small"] }
      - { label: "Заголовок", name: "heading", widget: "string" }
      - { label: "Текст", name: "body", widget: "markdown" }
      - { label: "Зображення", name: "image", widget: "image" }
      - label: "Таймер"
        name: "timer"
        widget: "object"
        fields:
          - { label: "Показати таймер", name: "show", widget: "boolean", default: false }
          - { label: "Дата закінчення", name: "end_date", widget: "datetime" }
