backend:
  name: git-gateway
  branch: main

media_folder: "static/images"    # куди зберігати завантажені файли
public_folder: "/images"         # як їх бачить фронтенд

collections:
  - name: "pages"                # унікальна назва колекції
    label: "Pages"               # те, що видно в UI
    folder: "content/pages"      # каталог із markdown-файлами
    create: true                 # можна створювати нові
    slug: "{{slug}}"             # URL-ім'я сторінки
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body",  name: "body",  widget: "markdown" }
